const STORAGE_KEYS={user:'taksinaka_user',bookings:'taksinaka_bookings'};
const rooms=[
 {id:'P101',name:'ห้องพักเดี่ยว P101',category:'room',type:'ธรรมดา',price:1200,detail:'พักได้ 1-2 คน พร้อมเครื่องใช้พื้นฐาน'},
 {id:'P102',name:'ห้องพักพรีเมียม P102',category:'room',type:'พรีเมียม',price:1800,detail:'ห้องพักพร้อมสิ่งอำนวยความสะดวก'},
 {id:'M101',name:'ห้องประชุม M101',category:'meeting',type:'ห้องประชุมเล็ก',price:1500,detail:'รองรับ 10-12 คน'},
 {id:'M201',name:'ห้องประชุม M201',category:'meeting',type:'ห้องประชุมกลาง',price:2800,detail:'รองรับ 20-25 คน'},
 {id:'H01',name:'หอประชุมใหญ่ H01',category:'hall',type:'หอประชุมใหญ่',price:30000,detail:'เหมาะสำหรับงานสัมมนา'}
];
const roles={
 customer:{label:'ลูกค้า',identity:'demo@taksin.ac.th',title:'เข้าสู่ระบบลูกค้า',description:'ค้นหา จองห้อง และติดตามประวัติการจอง'},
 staff:{label:'เจ้าหน้าที่',identity:'staff',title:'เข้าสู่ระบบเจ้าหน้าที่',description:'จัดการรายการจองและการชำระเงิน',target:'staff.html'},
 approver:{label:'ผู้อนุมัติ',identity:'approver',title:'เข้าสู่ระบบผู้อนุมัติ',description:'ตรวจสอบและอนุมัติคำขอจอง',target:'approver.html'},
 housekeeping:{label:'แม่บ้าน',identity:'housekeeping',title:'เข้าสู่ระบบแม่บ้าน',description:'ดูงานเตรียมห้องและสถานะห้อง',target:'housekeeping.html'}
};
const state={user:JSON.parse(localStorage.getItem(STORAGE_KEYS.user)||'null'),bookings:JSON.parse(localStorage.getItem(STORAGE_KEYS.bookings)||'[]'),selectedRoom:rooms[0],selectedPayment:'deposit',pendingBookingId:null};
const $=id=>document.getElementById(id);
const money=value=>`${Number(value||0).toLocaleString()} บาท`;
function save(){localStorage.setItem(STORAGE_KEYS.user,JSON.stringify(state.user));localStorage.setItem(STORAGE_KEYS.bookings,JSON.stringify(state.bookings));}
function setStatus(id,message,type='info'){const el=$(id);if(el){el.className=`status-box ${type}`;el.textContent=message;}}
function showView(view){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${view}`));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='search')renderRooms();if(view==='history')renderHistory();if(view==='booking')renderBooking();}
function updateUser(){if(!$('userBadge'))return;$('userBadge').textContent=state.user?`${state.user.name} (${state.user.role})`:'ยังไม่ได้เข้าสู่ระบบ';$('loginButton').style.display=state.user?'none':'inline-flex';$('logoutButton').style.display=state.user?'inline-flex':'none';}
function setRole(role){const p=roles[role]||roles.customer;$('loginRole').value=role;$('loginIdentity').value=p.identity;$('identityLabel').textContent=role==='customer'?'อีเมล / เบอร์โทร':'ชื่อผู้ใช้';$('roleHint').innerHTML=`<strong>${p.title}</strong><br>${p.description}`;document.querySelector('.login-submit').textContent=p.title;document.querySelectorAll('.role-option').forEach(b=>{const active=b.dataset.role===role;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false');});}
function paymentOptions(room){const total=Number(room.price);const list=[{value:'deposit',label:'ชำระมัดจำ 30%',amount:Math.round(total*.3),status:'รอชำระมัดจำ'},{value:'full',label:'ชำระเต็ม 100%',amount:total,status:'รอชำระเต็มจำนวน'}];if(room.category==='room')list.push({value:'counter',label:'ชำระที่เคาน์เตอร์',amount:total,status:'รอชำระที่เคาน์เตอร์'});return list;}
function currentBooking(){return state.bookings.find(b=>b.id===state.pendingBookingId);}
function renderInvoice(booking){const invoice=$('invoiceContainer');if(!invoice)return;const room=state.selectedRoom;const option=paymentOptions(room).find(o=>o.value===booking.paymentMethod)||paymentOptions(room)[0];const alreadySent=booking.paymentStatus==='รอตรวจสอบการชำระเงิน';invoice.innerHTML=`<div class="invoice-box"><h3>ใบแจ้งชำระเงิน</h3><div class="invoice-line"><span>รหัสการจอง</span><strong>${booking.id}</strong></div><div class="invoice-line"><span>รายการ</span><strong>${room.name}</strong></div><div class="invoice-line"><span>วิธีชำระ</span><strong>${option.label}</strong></div><div class="invoice-line"><span>ยอดที่ต้องชำระ</span><strong>${money(option.amount)}</strong></div><div class="invoice-line"><span>สถานะ</span><strong>${booking.paymentStatus||option.status}</strong></div>${booking.paymentMethod==='counter'?'<p class="payment-note">ชำระที่เคาน์เตอร์ในวันเข้าพัก</p>':`<div class="payment-box"><p>แนบสลิปเพื่อแจ้งชำระเงิน</p><div class="bank-box">ธนาคารตัวอย่าง เลขที่บัญชี 123-4-56789-0</div><div class="qr-box">QR CODE</div><label class="upload-label">แนบสลิป <input id="slipFile" type="file" accept="image/*"></label><button type="button" class="primary-btn full-width" id="payNowButton" ${alreadySent?'disabled':''}>${alreadySent?'ส่งหลักฐานแล้ว':'แจ้งชำระเงิน'}</button></div>`}</div>`;const pay=$('payNowButton');if(pay&&!alreadySent)pay.onclick=()=>{const file=$('slipFile');if(!file||!file.files.length){setStatus('loginStatus','กรุณาแนบสลิปก่อนแจ้งชำระเงิน','error');return;}booking.paymentStatus='รอตรวจสอบการชำระเงิน';booking.status='ส่งหลักฐานการชำระเงินแล้ว';save();renderInvoice(booking);renderHistory();alert('แจ้งชำระเงินแล้ว เจ้าหน้าที่จะตรวจสอบสลิป');};}
function renderBooking(){const room=state.selectedRoom||rooms[0];const container=$('bookingFormContainer');if(!container)return;const options=paymentOptions(room);if(!options.some(o=>o.value===state.selectedPayment))state.selectedPayment='deposit';container.innerHTML=`<form id="bookingForm"><div class="form-row"><label>ห้องที่เลือก</label><input value="${room.name}" readonly></div><div class="form-row"><label>วันที่เข้าพัก / ใช้ห้อง</label><input id="bookingDate" type="date" value="${new Date(Date.now()+86400000).toISOString().slice(0,10)}" required></div><div class="form-row"><label>จำนวนคืน / วัน</label><input id="bookingDuration" type="number" min="1" value="1" required></div><div class="payment-wrap"><label>เลือกวิธีชำระเงิน</label><div class="payment-options">${options.map(o=>`<button type="button" class="payment-option ${state.selectedPayment===o.value?'selected':''}" data-payment="${o.value}"><span>${o.label}</span><strong>${money(o.amount)}</strong></button>`).join('')}</div></div><button type="submit" class="primary-btn full-width">ส่งคำขอจอง</button></form>`;document.querySelectorAll('.payment-option').forEach(b=>b.onclick=()=>{state.selectedPayment=b.dataset.payment;renderBooking();});$('bookingForm').onsubmit=e=>{e.preventDefault();if(!state.user){alert('กรุณาเข้าสู่ระบบก่อนทำการจอง');showView('auth');return;}const option=options.find(o=>o.value===state.selectedPayment)||options[0];const booking={id:`BK-${Date.now().toString().slice(-6)}`,roomId:room.id,roomName:room.name,type:room.type,date:$('bookingDate').value,duration:Number($('bookingDuration').value||1),paymentMethod:option.value,amount:option.amount,paymentStatus:option.value==='counter'?'รอชำระที่เคาน์เตอร์':option.status,status:'รอการชำระเงิน',customer:state.user.email};state.bookings.unshift(booking);state.pendingBookingId=booking.id;save();renderInvoice(booking);renderHistory();alert(`สร้างรายการจอง ${booking.id} แล้ว กรุณาดำเนินการชำระเงิน`);};const pending=currentBooking();renderInvoice(pending||{id:'ยังไม่สร้าง',roomName:room.name,paymentMethod:state.selectedPayment,paymentStatus:'เลือกวิธีชำระเงินและกดส่งคำขอจอง'});}
function renderRooms(){const type=$('searchType')?.value||'all';const result=$('roomResults');if(!result)return;result.innerHTML=rooms.filter(r=>type==='all'||r.category===type).map(r=>`<article class="room-card"><div class="room-card-header"><h4>${r.name}</h4><span class="tag">${r.type}</span></div><p>${r.detail}</p><div class="room-meta"><strong>${money(r.price)}</strong><span>ว่าง</span></div><button class="primary-btn" type="button" data-room-id="${r.id}">เลือกห้อง</button></article>`).join('');document.querySelectorAll('[data-room-id]').forEach(b=>b.onclick=()=>{state.selectedRoom=rooms.find(r=>r.id===b.dataset.roomId)||rooms[0];state.selectedPayment='deposit';state.pendingBookingId=null;showView('booking');});}
function renderHistory(){const list=$('historyList');if(!list)return;const mine=state.user?state.bookings.filter(b=>!b.customer||b.customer===state.user.email):state.bookings;list.innerHTML=mine.length?mine.map(b=>`<div class="history-item"><div><strong>${b.roomName}</strong><small>รหัส ${b.id} | ${b.date||''}</small></div><div class="history-meta"><span>${b.paymentStatus||b.status}</span><strong>${money(b.amount)}</strong></div></div>`).join(''):'<div class="empty-state">ยังไม่มีประวัติการจอง</div>';}
function init(){document.querySelectorAll('.role-option').forEach(b=>b.onclick=()=>setRole(b.dataset.role));$('loginForm')?.addEventListener('submit',e=>{e.preventDefault();const role=$('loginRole').value,p=roles[role],identity=$('loginIdentity').value.trim();if(!p||identity!==p.identity||$('loginPassword').value!=='123456'){setStatus('loginStatus','ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง','error');return;}state.user={name:p.label,email:p.identity,role};save();updateUser();setStatus('loginStatus','เข้าสู่ระบบสำเร็จ','success');if(p.target)window.location.assign(p.target);else showView('home');});$('loginButton')?.addEventListener('click',()=>showView('auth'));$('logoutButton')?.addEventListener('click',()=>{state.user=null;save();updateUser();showView('home');});$('searchForm')?.addEventListener('submit',e=>{e.preventDefault();renderRooms();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.target==='searchPanel'?'search':b.dataset.target==='historyPanel'?'history':'auth')));setRole('customer');renderRooms();renderBooking();renderHistory();updateUser();showView('home');}
document.addEventListener('DOMContentLoaded',init);
