const approvalSeed=[{id:'ED-01',subject:'ขอใช้ห้องประชุมสำหรับกิจกรรมปฐมนิเทศ',requester:'คณะวิทยาศาสตร์',date:'วันนี้',detail:'ขอใช้ห้องประชุม M201 วันที่ 15 ตุลาคม 2569 เวลา 08:00-16:00 น. เพื่อจัดกิจกรรมปฐมนิเทศนักศึกษาใหม่',amount:'ขอลดหย่อนค่าใช้ห้อง 20%',steps:['หัวหน้าหน่วยงาน','ผู้อำนวยการ','ผู้อนุมัติหลัก'],current:2,status:'รอผู้อนุมัติ'} ,{id:'ED-02',subject:'ขอใช้หอประชุมใหญ่สำหรับงานมหาวิทยาลัย',requester:'กองกิจการนักศึกษา',date:'เมื่อวาน',detail:'ขอใช้หอประชุมใหญ่ H01 สำหรับงานพิธีการประจำปี พร้อมขออนุมัติค่าใช้จ่ายตามโครงการ',amount:'ไม่มี',steps:['หัวหน้าหน่วยงาน','ผู้บริหาร'],current:1,status:'รอผู้อนุมัติ'}];
const roomSeed=[{id:'HK-01',room:'P101',type:'ห้องพักเดี่ยว',guest:'สมชาย ใจดี',date:'วันนี้',detail:'ทำความสะอาด เปลี่ยนผ้าปูที่นอน และตรวจสอบเครื่องปรับอากาศ',status:'รอเตรียมห้อง'},{id:'HK-02',room:'P102',type:'ห้องพักพรีเมียม',guest:'มานี มีสุข',date:'พรุ่งนี้',detail:'เตรียมห้องพร้อมอาหารเช้าและตรวจสอบอุปกรณ์ภายในห้อง',status:'กำลังเตรียม'}];
const key='taksinakan_workflow';const db=JSON.parse(localStorage.getItem(key)||'null')||{approvals:approvalSeed,rooms:roomSeed};const $=id=>document.getElementById(id);const save=()=>localStorage.setItem(key,JSON.stringify(db));const toast=msg=>{const el=$('workflowToast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};const badge=s=>`<span class="badge ${s.includes('อนุมัติ')||s.includes('พร้อม')?'confirmed':'pending'}">${s}</span>`;
function renderApprover(){if(!$('approvalList'))return;$('pendingCount').textContent=db.approvals.filter(x=>x.status==='รอผู้อนุมัติ').length;$('approvalList').innerHTML=db.approvals.map(x=>`<div class="workflow-item" data-id="${x.id}"><div class="workflow-item-top"><strong>${x.id} ${x.subject}</strong>${badge(x.status)}</div><p>${x.requester}</p><div class="workflow-meta"><span>วันที่: ${x.date}</span><span>ลำดับที่ ${x.current}/${x.steps.length}</span></div></div>`).join('')||'<div class="workflow-empty">ไม่มีหนังสือรอตรวจสอบ</div>';document.querySelectorAll('#approvalList .workflow-item').forEach(el=>el.onclick=()=>showApproval(el.dataset.id));}
function showApproval(id){const x=db.approvals.find(a=>a.id===id);if(!x)return;document.querySelectorAll('#approvalList .workflow-item').forEach(el=>el.classList.toggle('selected',el.dataset.id===id));$('approvalDetail').innerHTML=`<h2>รายละเอียดคำขอ</h2><div class="workflow-detail"><div class="workflow-detail-box"><strong>${x.id} ${x.subject}</strong><p>${x.detail}</p><div class="workflow-meta"><span>ผู้ขอ: ${x.requester}</span><span>วันที่: ${x.date}</span><span>ค่าใช้จ่าย: ${x.amount}</span><span>สถานะ: ${x.status}</span></div></div><div><strong>ลำดับการอนุมัติ</strong><div class="workflow-progress">${x.steps.map((s,i)=>`<span class="workflow-step ${i<x.current?'active':''}">${i+1}. ${s}</span>`).join('')}</div></div><div class="workflow-actions"><button class="primary-btn" onclick="approve('${x.id}')">✍️ ลงนามอนุมัติ</button><button class="ghost-btn" onclick="reject('${x.id}')">ไม่อนุมัติ</button></div></div>`;}
function approve(id){const x=db.approvals.find(a=>a.id===id);if(!x)return;if(x.current<x.steps.length){x.current+=1;x.status=x.current>=x.steps.length?'อนุมัติแล้ว':'ส่งต่อผู้อนุมัติลำดับถัดไป';}save();renderApprover();showApproval(id);toast(x.status==='อนุมัติแล้ว'?'อนุมัติครบทุกลำดับแล้ว':'ลงนามแล้ว ระบบส่งต่อให้ผู้อนุมัติลำดับถัดไป');}function reject(id){const x=db.approvals.find(a=>a.id===id);x.status='ไม่อนุมัติ';save();renderApprover();showApproval(id);toast('บันทึกผลไม่อนุมัติแล้ว');}
function renderHousekeeping(){if(!$('roomTaskList'))return;$('readyCount').textContent=db.rooms.filter(x=>x.status!=='พร้อมใช้งาน').length;$('roomTaskList').innerHTML=db.rooms.map(x=>`<div class="workflow-item" data-id="${x.id}"><div class="workflow-item-top"><strong>${x.room} ${x.type}</strong>${badge(x.status)}</div><p>${x.detail}</p><div class="workflow-meta"><span>ผู้เข้าพัก: ${x.guest}</span><span>เข้าพัก: ${x.date}</span></div></div>`).join('');document.querySelectorAll('#roomTaskList .workflow-item').forEach(el=>el.onclick=()=>showRoom(el.dataset.id));}
function showRoom(id){const x=db.rooms.find(r=>r.id===id);if(!x)return;document.querySelectorAll('#roomTaskList .workflow-item').forEach(el=>el.classList.toggle('selected',el.dataset.id===id));$('roomDetail').innerHTML=`<h2>รายละเอียดห้อง</h2><div class="workflow-detail"><div class="workflow-detail-box"><strong>${x.room} - ${x.type}</strong><p>${x.detail}</p><div class="workflow-meta"><span>ผู้เข้าพัก: ${x.guest}</span><span>วันที่เข้าพัก: ${x.date}</span><span>สถานะ: ${x.status}</span></div></div><div class="workflow-actions"><button class="primary-btn" onclick="markReady('${x.id}')">✅ อัปเดตเป็นพร้อมใช้งาน</button><button class="secondary-btn" onclick="toast('รับงานเตรียมห้องแล้ว')">รับงาน</button></div></div>`;}
function markReady(id){const x=db.rooms.find(r=>r.id===id);x.status='พร้อมใช้งาน';save();renderHousekeeping();showRoom(id);toast(`ห้อง ${x.room} พร้อมใช้งานแล้ว แจ้งเจ้าหน้าที่และลูกค้าเรียบร้อย`);}
if($('approvalList')){save();renderApprover();}if($('roomTaskList')){save();renderHousekeeping();}
